### ISSUE TITLE
[PP] KeyError in delete_schema_mssa_links 

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3584]
From [Slack thread](https://getdbt.slack.com/archives/C2JRRQDTL/p1626380641235500):

> Yes I was editing a test that applied to a source. I only ran into this issue for custom generic tests that apply to sources

```
2021-07-15 20:41:44.027209 (MainThread): Encountered an error:
2021-07-15 20:41:44.027763 (MainThread): 'sources'
2021-07-15 20:41:44.032374 (MainThread): Traceback (most recent call last):
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/main.py", line 125, in main
    results, succeeded = handle_and_check(args)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/main.py", line 203, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/main.py", line 256, in run_from_args
    results = task.run()
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/task/runnable.py", line 406, in run
    self._runtime_initialize()
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/task/runnable.py", line 122, in _runtime_initialize
    super()._runtime_initialize()
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/task/runnable.py", line 79, in _runtime_initialize
    self.load_manifest()
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/task/runnable.py", line 66, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/parser/manifest.py", line 170, in get_full_manifest
    manifest = loader.load()
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/parser/manifest.py", line 212, in load
    project_parser_files = partial_parsing.get_parsing_files()
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/parser/partial.py", line 131, in get_parsing_files
    self.update_in_saved(file_id)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/parser/partial.py", line 201, in update_in_saved
    self.update_macro_in_saved(new_source_file, old_source_file)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/parser/partial.py", line 254, in update_macro_in_saved
    self.handle_macro_file_links(old_source_file, follow_references=True)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/parser/partial.py", line 360, in handle_macro_file_links
    self.schedule_macro_nodes_for_parsing(referencing_nodes)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/parser/partial.py", line 390, in schedule_macro_nodes_for_parsing
    self.delete_schema_mssa_links(schema_file, key, node_patch)
  File "/Users/<user>/Library/Python/3.7/lib/python/site-packages/dbt/parser/partial.py", line 578, in delete_schema_mssa_links
    prefix = key_to_prefix[dict_key]
KeyError: 'sources' 
```

**Comment by gshank** [comment]
Missing key. Easy fix.

**Comment by gshank** [comment]
The code to remove related nodes (etc) when test macros are re-done was not handling source tests.
