### ISSUE TITLE
[PP] delete_schema_macro_patch: local variable 'macro_unique_id' referenced before assignment

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3627]
Bug crops up in this line, if the condition in the previous for loop is never met:
https://github.com/dbt-labs/dbt/blob/72722635f275666b34efc9baf8485be79dfcaa88/core/dbt/parser/partial.py#L643

```
2021-07-26 13:04:12.526071 (MainThread): Running with dbt=0.20.0
2021-07-26 13:04:12.722541 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.test.TestTask'>, data=False, debug=False, defer=None, exclude=None, fail_fast=False, log_cache_events=False, log_format='default', models=None, partial_parse=None, profile=None, profiles_dir='/Users/jerco/.dbt', project_dir=None, record_timing_info=None, rpc_method='test', schema=False, selector_name=None, single_threaded=False, state=None, store_failures=True, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, use_colors=None, use_experimental_parser=False, vars='{}', version_check=True, warn_error=False, which='test', write_json=True)
2021-07-26 13:04:12.724824 (MainThread): Tracking: tracking
2021-07-26 13:04:12.753859 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088752e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b2cf10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b4eac0>]}
2021-07-26 13:04:12.841350 (MainThread): Partial parsing enabled: 2 files deleted, 1 files added, 0 files changed.
2021-07-26 13:04:12.841663 (MainThread): Partial parsing: added file: my_project://models/sources.yml
2021-07-26 13:04:12.841937 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c093a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c09430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c093d0>]}
2021-07-26 13:04:12.842190 (MainThread): Flushing usage events
2021-07-26 13:04:13.126158 (MainThread): Encountered an error:
2021-07-26 13:04:13.126434 (MainThread): local variable 'macro_unique_id' referenced before assignment
2021-07-26 13:04:13.131442 (MainThread): Traceback (most recent call last):
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/main.py", line 125, in main
    results, succeeded = handle_and_check(args)
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/main.py", line 203, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/main.py", line 256, in run_from_args
    results = task.run()
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/task/runnable.py", line 406, in run
    self._runtime_initialize()
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/task/runnable.py", line 122, in _runtime_initialize
    super()._runtime_initialize()
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/task/runnable.py", line 79, in _runtime_initialize
    self.load_manifest()
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/task/runnable.py", line 66, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/parser/manifest.py", line 170, in get_full_manifest
    manifest = loader.load()
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/parser/manifest.py", line 212, in load
    project_parser_files = partial_parsing.get_parsing_files()
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/parser/partial.py", line 127, in get_parsing_files
    self.delete_schema_file(file_id)
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/parser/partial.py", line 447, in delete_schema_file
    self.handle_schema_file_changes(saved_schema_file, saved_yaml_dict, new_yaml_dict)
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/parser/partial.py", line 499, in handle_schema_file_changes
    self.delete_schema_macro_patch(schema_file, macro)
  File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/parser/partial.py", line 643, in delete_schema_macro_patch
    if macro_unique_id and macro_unique_id in self.saved_manifest.macros:
UnboundLocalError: local variable 'macro_unique_id' referenced before assignment
```

**Comment by jtcohen6** [comment]
I came across this bug this morning. I tried retracing my steps, but I haven't been able to reproduce it. I'm happy closing this one for now, and coming back to it if we see the same error crop up again later.

**Comment by gshank** [comment]
I think I've found it. We weren't scheduling the new macro file for parsing, so it was trying to process a macro_patch that was already handled.
