### ISSUE TITLE
rpc server intermittently fails to compile with error of "argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by tom-james-watson** [dbt-labs/dbt#3734]
### Describe the bug

We are starting an rpc server and having it intermittently fail to compile with `argument of type 'NoneType' is not iterable`. This message is what is returned on `body.result.error` in the response of a call of method `status` to the rpc server. All that we are doing before getting this error is starting the rpc server and then polling `status` to wait for it to be ready.

This seems to only happen with `0.20.0` - we have never seen this behaviour before this version. 

We use the rpc server in our application to provide some dbt functionality. The issue happens intermittently with real projects, but I have not been able to correlate anything that makes it specifically happen. I would say 95% of the time, it does not happen and the rpc server compiles the project successfully. It consistently happens in our integration tests that run against a modified version of dbt-starter-project when run on circle ci, though the same tests work fine locally. To me it has all the signs of some kind of race condition.

The (debug) logs returned from `status` when it fails are:

```
      Partial parsing not enabled
      Parsing macros/adapters.sql
      Parsing macros/catalog.sql
      Parsing macros/relations.sql
      Parsing macros/materializations/snapshot_merge.sql
      Parsing macros/core.sql
      Parsing macros/adapters/common.sql
      Parsing macros/etc/datetime.sql
      Parsing macros/etc/get_custom_alias.sql
      Parsing macros/etc/get_custom_database.sql
      Parsing macros/etc/get_custom_schema.sql
      Parsing macros/etc/is_incremental.sql
      Parsing macros/etc/query.sql
      Parsing macros/materializations/helpers.sql
      Parsing macros/materializations/test.sql
      Parsing macros/materializations/common/merge.sql
      Parsing macros/materializations/incremental/helpers.sql
      Parsing macros/materializations/incremental/incremental.sql
      Parsing macros/materializations/seed/seed.sql
      Parsing macros/materializations/snapshot/snapshot.sql
      Parsing macros/materializations/snapshot/snapshot_merge.sql
      Parsing macros/materializations/snapshot/strategies.sql
      Parsing macros/materializations/table/table.sql
      Parsing macros/materializations/view/create_or_replace_view.sql
      Parsing macros/materializations/view/view.sql
      Parsing macros/schema_tests/accepted_values.sql
      Parsing macros/schema_tests/not_null.sql
      Parsing macros/schema_tests/relationships.sql
      Parsing macros/schema_tests/unique.sql
```

### System information

**Which database are you using dbt with?**

These are the drivers where we have seen this bug happen, but that doesn't necessarily mean it doesn't also happen on other drivers:

- [x] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

```
0.20.0
```

**The operating system you're using:**

macOS 11.4 and multiple versions of linux (lets say Ubuntu 18.04 and 20.04 for simplicity).

**The output of `python --version`:**

3.6

### Additional context

In the context of our app, dbt is being run from a standalone binary that has been packaged with https://pyinstaller.readthedocs.io. I am currently doing some work to build this binary on python 3.9 to see if that magically helps the issue.

**Comment by tom-james-watson** [comment]
I can confirm that with python 3.9 we see the same issue.

**Comment by tom-james-watson** [comment]
We're also seeing this with the 0.20.1, which has just been released.

**Comment by jtcohen6** [comment]
@tom-james-watson Thanks for opening, and for sharing all those details; sorry to hear you're running into this. I'm not sure what's going on, but I'll share as much context as I can.

```
argument of type 'NoneType' is not iterable
```
It would've been neat if https://github.com/dbt-labs/dbt/issues/3568 were the root cause here, but:
- I don't believe the starter project has any fully-commented-out yaml files
- We have a fix for that in v0.20.1, and it sounds like you're still seeing the bug after upgrading

There are two changes in v0.20.0 that are _possibly_ related:
- The addition of the `list` method (https://github.com/dbt-labs/dbt/pull/3384)
- Raising an error at invocation start (including on RPC server start-up) if there are more packages defined in `packages.yml` than are installed in the `dbt_modules` directory (https://github.com/dbt-labs/dbt/pull/3343). This should raise a different error... but _maybe_ it reflects the fact that the `packages` array is None?

I will say that the dbt Cloud IDE leans heavily on the RPC server, and I haven't heard any reports to date of elevated error rates, or of that error message in particular, for folks using dbt v0.20.0.

So, in the hopes of finding some sort of definite lead: When this fails, is the last debug-level log message always `Parsing macros/schema_tests/unique.sql`?

**Comment by tom-james-watson** [comment]
> So, in the hopes of finding some sort of definite lead: When this fails, is the last debug-level log message always `Parsing macros/schema_tests/unique.sql`

Every time I have seen it on projects that are very lightly modified dbt-starter-projects in our tests, yeah. If I manage to catch it again in the real world I will need to check if that is also the case. It's proving very hard to reliably reproduce outside of our CI tests, though.

I guess what would be ideal is if there is some way for us to actually produce a stack trace for the error? Is there some way of doing that? Running the rpc server with `--debug` doesn't seem to help. Thanks!

**Comment by jtcohen6** [comment]
@tom-james-watson Totally, I think that's the right instinct. I do believe it's possible to grab the traceback from:
- the log file (`logs/dbt.log`)
- stdout logs by running `dbt --debug rpc`

E.g. when I spin up an RPC server and poll for a nonexistent `request_token`, I see this in `logs/dbt.log`:

```
2021-08-23 08:28:59.763237 (Thread-2): API Exception: {'type': 'UnknownAsyncIDException', 'args': (UUID('14a45128-93ab-403d-9abf-991bbfbce6e6'),), 'message': 'RPC server got an unknown async ID: 14a45128-93ab-403d-9abf-991bbfbce6e6'}
Traceback (most recent call last):
  File "/usr/local/Cellar/dbt/0.20.1_1/libexec/lib/python3.8/site-packages/jsonrpc/manager.py", line 113, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/usr/local/Cellar/dbt/0.20.1_1/libexec/lib/python3.8/site-packages/dbt/rpc/method.py", line 118, in __call__
    return self.handle_request()
  File "/usr/local/Cellar/dbt/0.20.1_1/libexec/lib/python3.8/site-packages/dbt/rpc/builtins.py", line 193, in handle_request
    task: RequestTaskHandler = self.task_manager.get_request(task_id)
  File "/usr/local/Cellar/dbt/0.20.1_1/libexec/lib/python3.8/site-packages/dbt/rpc/task_manager.py", line 142, in get_request
    raise dbt.exceptions.UnknownAsyncIDException(task_id) from None
dbt.exceptions.UnknownAsyncIDException: RPC server got an unknown async ID: 14a45128-93ab-403d-9abf-991bbfbce6e6
2021-08-23 08:28:59.766321 (Thread-2): sending response (<Response 300 bytes [200 OK]>) to 127.0.0.1
```

I see the same level of detail in stdout logging if I spin up the RPC server with the `--debug` flag (check `exc_info` in the first line):
```json
{"timestamp": "2021-08-23T08:28:59.763237Z", "message": "API Exception: {'type': 'UnknownAsyncIDException', 'args': (UUID('14a45128-93ab-403d-9abf-991bbfbce6e6'),), 'message': 'RPC server got an unknown async ID: 14a45128-93ab-403d-9abf-991bbfbce6e6'}", "channel": "jsonrpc.manager", "level": 10, "levelname": "DEBUG", "thread_name": "Thread-2", "process": 76397, "extra": {"stack_info": null, "request_id": "2db9a2fe-9a39-41ef-828c-25e04dd6b07d", "method": "poll", "context": "request", "addr": "127.0.0.1", "http_method": "POST", "run_state": "internal", "old_level": 14}, "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/Cellar/dbt/0.20.1_1/libexec/lib/python3.8/site-packages/jsonrpc/manager.py\", line 113, in _get_responses\n    result = method(*request.args, **request.kwargs)\n  File \"/usr/local/Cellar/dbt/0.20.1_1/libexec/lib/python3.8/site-packages/dbt/rpc/method.py\", line 118, in __call__\n    return self.handle_request()\n  File \"/usr/local/Cellar/dbt/0.20.1_1/libexec/lib/python3.8/site-packages/dbt/rpc/builtins.py\", line 193, in handle_request\n    task: RequestTaskHandler = self.task_manager.get_request(task_id)\n  File \"/usr/local/Cellar/dbt/0.20.1_1/libexec/lib/python3.8/site-packages/dbt/rpc/task_manager.py\", line 142, in get_request\n    raise dbt.exceptions.UnknownAsyncIDException(task_id) from None\ndbt.exceptions.UnknownAsyncIDException: RPC server got an unknown async ID: 14a45128-93ab-403d-9abf-991bbfbce6e6"}
{"timestamp": "2021-08-23T08:28:59.766321Z", "message": "sending response (<Response 300 bytes [200 OK]>) to 127.0.0.1", "channel": "dbt", "level": 11, "levelname": "INFO", "thread_name": "Thread-2", "process": 76397, "extra": {"response_code": 200, "request_id": "2db9a2fe-9a39-41ef-828c-25e04dd6b07d", "addr": "127.0.0.1", "http_method": "POST", "context": "server", "run_state": "internal"}}
```

**Comment by tom-james-watson** [comment]
Unfortunately it looks like the error is not making it into logs.

If I look in `logs/dbt.log` I see the following:

```
cat logs/dbt.log 
2021-08-31 10:20:53.216041 (MainThread): Running with dbt=0.20.1
2021-08-31 10:20:53.295153 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.rpc.server.RPCServerTask'>, debug=True, defer=None, exclude=None, host='0.0.0.0', log_cache_events=False, log_format='text', models=None, partial_parse=None, port=8581, profile='default', profiles_dir='<A PATH TO A TMP DIR WHERE WE WRITE PROFILES>', project_dir=None, record_timing_info=None, rpc_method=None, single_threaded=False, state=None, strict=False, target='default', test_new_parser=False, threads=None, use_cache=True, use_colors=None, use_experimental_parser=False, vars='{}', version_check=True, warn_error=False, which='rpc', write_json=True)
2021-08-31 10:20:53.295916 (MainThread): Tracking: tracking
2021-08-31 10:20:53.303762 (Thread-1): Partial parsing not enabled
2021-08-31 10:20:53.304657 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb63a0e3978>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb6386bd908>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb63a0e3b70>]}
2021-08-31 10:20:53.305314 (MainThread): Serving RPC server at 0.0.0.0:8581, pid=377759
2021-08-31 10:20:53.305529 (MainThread): Supported methods: ['cli_args', 'compile', 'compile_sql', 'deps', 'docs.generate', 'gc', 'get-manifest', 'kill', 'list', 'poll', 'ps', 'run', 'run-operation', 'run_sql', 'seed', 'snapshot', 'snapshot-freshness', 'status', 'test']
2021-08-31 10:20:53.305781 (MainThread): Send requests to http://localhost:8581/jsonrpc
2021-08-31 10:20:53.314767 (Thread-1): Parsing macros/catalog.sql
2021-08-31 10:20:53.318139 (Thread-1): Parsing macros/relations.sql
2021-08-31 10:20:53.320074 (Thread-1): Parsing macros/adapters.sql
2021-08-31 10:20:53.345422 (Thread-1): Parsing macros/materializations/snapshot_merge.sql
2021-08-31 10:20:53.348242 (Thread-1): Parsing macros/core.sql
2021-08-31 10:20:53.353609 (Thread-1): Parsing macros/materializations/test.sql
2021-08-31 10:20:53.363344 (Thread-1): Parsing macros/materializations/helpers.sql
2021-08-31 10:20:53.375746 (Thread-1): Parsing macros/materializations/common/merge.sql
2021-08-31 10:20:53.393402 (Thread-1): Parsing macros/materializations/snapshot/snapshot.sql
2021-08-31 10:20:53.431900 (Thread-1): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-08-31 10:20:53.434685 (Thread-1): Parsing macros/materializations/snapshot/strategies.sql
2021-08-31 10:20:53.458400 (Thread-1): Parsing macros/materializations/table/table.sql
2021-08-31 10:20:53.467805 (Thread-1): Parsing macros/materializations/seed/seed.sql
2021-08-31 10:20:53.505892 (Thread-1): Parsing macros/materializations/incremental/incremental.sql
2021-08-31 10:20:53.516355 (Thread-1): Parsing macros/materializations/incremental/helpers.sql
2021-08-31 10:20:53.519385 (Thread-1): Parsing macros/materializations/view/create_or_replace_view.sql
2021-08-31 10:20:53.526405 (Thread-1): Parsing macros/materializations/view/view.sql
2021-08-31 10:20:53.534829 (Thread-1): Parsing macros/schema_tests/accepted_values.sql
2021-08-31 10:20:53.538331 (Thread-1): Parsing macros/schema_tests/unique.sql
2021-08-31 10:20:53.540702 (Thread-1): Parsing macros/schema_tests/not_null.sql
2021-08-31 10:20:53.542974 (Thread-1): Parsing macros/schema_tests/relationships.sql
2021-08-31 10:20:53.546193 (Thread-1): Parsing macros/etc/datetime.sql
2021-08-31 10:20:53.557981 (Thread-1): Parsing macros/etc/get_custom_alias.sql
2021-08-31 10:20:53.559292 (Thread-1): Parsing macros/etc/get_custom_database.sql
2021-08-31 10:20:53.561976 (Thread-1): Parsing macros/etc/is_incremental.sql
2021-08-31 10:20:53.564745 (Thread-1): Parsing macros/etc/get_custom_schema.sql
2021-08-31 10:20:53.567998 (Thread-1): Parsing macros/etc/query.sql
2021-08-31 10:20:53.569708 (Thread-1): Parsing macros/adapters/common.sql
2021-08-31 10:20:53.886693 (Thread-2): handling status request
2021-08-31 10:20:53.886873 (Thread-2): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '253ed208-64e3-4f9c-a21c-093cf70f974e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb638669f60>]}
2021-08-31 10:20:53.887768 (Thread-2): sending response (<Response 8211 bytes [200 OK]>) to 127.0.0.1
2021-08-31 10:20:55.401399 (Thread-3): handling status request
2021-08-31 10:20:55.401678 (Thread-3): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '253ed208-64e3-4f9c-a21c-093cf70f974e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb638676438>]}
2021-08-31 10:20:55.402492 (Thread-3): sending response (<Response 8211 bytes [200 OK]>) to 127.0.0.1
```

And the actual logs returned from rpc are:

```
Partial parsing not enabled                                    
Parsing macros/catalog.sql                                     
Parsing macros/relations.sql                                   
Parsing macros/adapters.sql                                    
Parsing macros/materializations/snapshot_merge.sql             
Parsing macros/core.sql                                        
Parsing macros/materializations/test.sql                       
Parsing macros/materializations/helpers.sql                    
Parsing macros/materializations/common/merge.sql               
Parsing macros/materializations/snapshot/snapshot.sql          
Parsing macros/materializations/snapshot/snapshot_merge.sql    
Parsing macros/materializations/snapshot/strategies.sql        
Parsing macros/materializations/table/table.sql                
Parsing macros/materializations/seed/seed.sql                  
Parsing macros/materializations/incremental/incremental.sql    
Parsing macros/materializations/incremental/helpers.sql        
Parsing macros/materializations/view/create_or_replace_view.sql
Parsing macros/materializations/view/view.sql                  
Parsing macros/schema_tests/accepted_values.sql                
Parsing macros/schema_tests/unique.sql                         
Parsing macros/schema_tests/not_null.sql                       
Parsing macros/schema_tests/relationships.sql                  
Parsing macros/etc/datetime.sql                                
Parsing macros/etc/get_custom_alias.sql                        
Parsing macros/etc/get_custom_database.sql                     
Parsing macros/etc/is_incremental.sql                          
Parsing macros/etc/get_custom_schema.sql                       
Parsing macros/etc/query.sql                                   
Parsing macros/adapters/common.sql                             
```

Right now I'm trying to create a minimal reproduction to help narrow it down, though I'm struggling to recreate the issue when isolated from the rest of our codebase. I'm still working on it.

Interestingly, to recreate the issue I need to remove the `logs` directory of the target project. Manually running dbt rpc on a project without a `logs` dir works fine though, so I'm trying to work out where the difference is with how we are calling into dbt in our codebase. But yeah that's potentially an interesting lead on where the error is coming from.

**Comment by tom-james-watson** [comment]
I've finally managed to debug what was causing this. In our app, when we detect that files in the dbt project change, we restart the rpc server with a SIGHUP. We ignore things that are build artifacts or logs, but weren't ignoring the creation of the logs directory itself. This was causing us to send a SIGHUP to the rpc server whilst it was compiling. Obviously pre-0.20.0 this didn't do anything, but since 0.20.0 it causes the above exception. The bug here is obviously on our side, however it looks like at least there could be some improved handling of exceptions needed in this case on your side? I'm not sure if you prefer to convert this into an issue for investigating that, or close it out - I'll leave that up to you. Thanks for your help.

**Comment by jtcohen6** [comment]
@tom-james-watson If I understand you right, sending a SIGHUP while the RPC server is compiling started causing this error in v0.20.0. I'm happy to leave this issue open, since it represents a real usability challenge in the RPC server today.

To be transparent, the RPC server overall does not have the same stability commitments as dbt-core. That's increasingly important as we approach the release of dbt-core v1.0. We're soon looking to move the RPC server code out of this codebase (#3501, #3675), and we have plans to significantly rework it over the next several months.
