### ISSUE TITLE
"dbt seed" command fails when running in dbt Cloud with timeout error on version .20.1-rc-1

### ISSUE THREAD

**Issue by codigo-ergo-sum** [dbt-labs/dbt#3740]
### Describe the bug
When I run a job in dbt cloud which has a step that calls "dbt seed" on version .20.1-rc-1, I receive an error message " initiate() got an unexpected keyword argument 'timeout'". The error doesn't occur if I run the exact same code in the exact same branch on .20.1-rc-1 on my local machine. This is with a BigQuery back-end.

The exact error is:

```
Compilation Error in macro bigquery__load_csv_rows (macros/materializations/seed.sql)
  initiate() got an unexpected keyword argument 'timeout'
  
  > in macro load_csv_rows (macros/materializations/seed/seed.sql)
  > called by macro materialization_seed_default (macros/materializations/seed/seed.sql)
  > called by macro bigquery__load_csv_rows (macros/materializations/seed.sql)
```

It happens with 7 or so different seed files, exact same error for each one of them.

### Steps To Reproduce
See above

### Expected behavior
Dbt seed runs successfully in dbt cloud

### Screenshots and log output
Here is a detailed stack trace from the console logs:

```
2021-08-13 15:34:41.026881 (Thread-16): Compilation Error in macro bigquery__load_csv_rows (macros/materializations/seed.sql)
  initiate() got an unexpected keyword argument 'timeout'
  
  > in macro load_csv_rows (macros/materializations/seed/seed.sql)
  > called by macro materialization_seed_default (macros/materializations/seed/seed.sql)
  > called by macro bigquery__load_csv_rows (macros/materializations/seed.sql)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 305, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 24, in macro
  File "/usr/local/lib/python3.8/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/bigquery/impl.py", line 737, in load_dataframe
    job = client.load_table_from_file(f, table, rewind=True,
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/bigquery/client.py", line 2416, in load_table_from_file
    response = self._do_resumable_upload(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/bigquery/client.py", line 2792, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/bigquery/client.py", line 2856, in _initiate_resumable_upload
    upload.initiate(
TypeError: initiate() got an unexpected keyword argument 'timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 348, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 291, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 393, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/run.py", line 249, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 90, in macro
  File "/usr/local/lib/python3.8/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 21, in macro
  File "/usr/local/lib/python3.8/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 262, in call_macro
    return e.value
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 307, in exception_handler
    raise_compiler_error(str(e), self.macro)
  File "/usr/local/lib/python3.8/dist-packages/dbt/exceptions.py", line 444, in raise_compiler_error
    raise CompilationException(msg, node)
dbt.exceptions.CompilationException: Compilation Error in macro bigquery__load_csv_rows (macros/materializations/seed.sql)
  initiate() got an unexpected keyword argument 'timeout'
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
.20.1-rc-1 (only on dbt cloud)
```

**The operating system you're using:**
Whatever dbt cloud is using

**The output of `python --version`:**
Whatever dbt cloud is using

**Comment by jtcohen6** [comment]
This was a bit of fishing expedition, but effectively:
- [`google.cloud.bigquery.client._initiate_resumable_upload()`](https://github.com/googleapis/python-bigquery/blob/v2.24.0/google/cloud/bigquery/client.py#L2872-L2879) calls `google.resumable_media.requests.ResumableUpload.initiate()`
- The `timeout` argument of `ResumableUpload.initiate()` was added in [the v0.6.0 release](https://github.com/googleapis/google-resumable-media-python/releases/tag/v0.6.0) of `google-resumable-media`

I just checked the requirements files in dbt Cloud, and found that:
- dbt v0.20.1-rc1` was installed in dbt Cloud with `google-cloud-bigquery==2.20.0` and `google-resumable-media==0.5.1`
- dbt v0.20.1 (just released + added!) pins it as `google-cloud-bigquery==2.24.0` and `google-resumable-media==1.3.3` (!)

For some reason, we had been using a quite-old version of `google-resumable-media==1.3.3` in the environment for dbt v0.20.1-rc1. Now that the final v0.20.1 is live in Cloud, the dependencies should be up to date. If all goes right, this error should just go away...

(cc @kwigley @GideonShils)

**Comment by jtcohen6** [comment]
Confirmed with @codigo-ergo-sum that this ran successfully with v0.20.1 (final), so I'm going to close :)
