### ISSUE TITLE
Partial parsing errors collected by event logging as of 10/04

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt#3996]
01
===================================================
line 236 in update_mssat_in_saved
parse_file_type = 'snapshot'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/manifest.py", line 224, in load
    project_parser_files = partial_parsing.get_parsing_files()
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 137, in get_parsing_files
    self.update_in_saved(file_id)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 217, in update_in_saved
    self.update_mssat_in_saved(new_source_file, old_source_file)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 236, in update_mssat_in_saved
    unique_id = old_source_file.nodes[0]
IndexError: list index out of range

Q: Do snapshots actually get saved in source_file.nodes?

02
====================================================
line 302 in schedule_referencing_nodes_for_parsing
parse_file_type = null
Traceback (most recent call last):
File "/.../.virtualenvs/dbt/lib/python3.9/site-packages/dbt/parser/manifest.py", line 224, in load
    project_parser_files = partial_parsing.get_parsing_files()
  File "/.../.virtualenvs/dbt/lib/python3.9/site-packages/dbt/parser/partial.py", line 134, in get_parsing_files
    self.delete_from_saved(file_id)
  File "/.../.virtualenvs/dbt/lib/python3.9/site-packages/dbt/parser/partial.py", line 198, in delete_from_saved
    self.remove_mssat_file(saved_source_file)
  File "/.../.virtualenvs/dbt/lib/python3.9/site-packages/dbt/parser/partial.py", line 297, in remove_mssat_file
    self.schedule_referencing_nodes_for_parsing(unique_id)
  File "/.../.virtualenvs/dbt/lib/python3.9/site-packages/dbt/parser/partial.py", line 302, in schedule_referencing_nodes_for_parsing
    self.schedule_nodes_for_parsing(self.saved_manifest.child_map[unique_id])
KeyError: 'model.data_warehouse.vp_creator_marketplace__user_dim'

03
=====================================================
line 264 in remove_node_in_saved
parse_file_type = null
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/manifest.py", line 224, in load
    project_parser_files = partial_parsing.get_parsing_files()  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 134, in get_parsing_files
    self.delete_from_saved(file_id)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 198, in delete_from_saved
    self.remove_mssat_file(saved_source_file)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 296, in remove_mssat_file
    self.remove_node_in_saved(source_file, unique_id)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 264, in remove_node_in_saved
    for elem in schema_file.dict_from_yaml[dict_key]:
KeyError: 'seeds'
KeyError: 'snapshots'

04
=====================================================
line 293 in remove_mssat_file
parse_file_type = null
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/manifest.py", line 224, in load
    project_parser_files = partial_parsing.get_parsing_files()
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 134, in get_parsing_files
    self.delete_from_saved(file_id)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 198, in delete_from_saved
    self.remove_mssat_file(saved_source_file)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 293, in remove_mssat_file
    raise Exception(f"No nodes found for source file {source_file.file_id}")
Exception: No nodes found for source file data_integration_hub_semantic://snapshots/snapshot_proximity.sql

05
=====================================================
ine 316 in schedule_nodes_for_parsing
parse_file_type = schema
Traceback (most recent call last):
  File "/.../dbt/core/dbt/parser/manifest.py", line 224, in load
    project_parser_files = partial_parsing.get_parsing_files()
  File "/.../dbt/core/dbt/parser/partial.py", line 128, in get_parsing_files
    self.change_schema_file(file_id)
  File "/.../dbt/co..re/dbt/parser/partial.py", line 475, in change_schema_file
    self.handle_schema_file_changes(saved_schema_file, saved_yaml_dict, new_yaml_dict)
  File "/.../dbt/core/dbt/parser/partial.py", line 521, in handle_schema_file_changes
    self.delete_schema_source(schema_file, source)
  File "/.../dbt/core/dbt/parser/partial.py", line 677, in delete_schema_source
    self.schedule_referencing_nodes_for_parsing(unique_id)
  File "/.../dbt/core/dbt/parser/partial.py", line 302, in schedule_referencing_nodes_for_parsing
    self.schedule_nodes_for_parsing(self.saved_manifest.child_map[unique_id])
  File "/.../dbt/core/dbt/parser/partial.py", line 316, in schedule_nodes_for_parsing
    self.remove_mssat_file(source_file)
  File "/.../dbt/core/dbt/parser/partial.py", line 297, in remove_mssat_file
    self.schedule_referencing_nodes_for_parsing(unique_id)
  File "/.../dbt/core/dbt/parser/partial.py", line 302, in schedule_referencing_nodes_for_parsing
    self.schedule_nodes_for_parsing(self.saved_manifest.child_map[unique_id])
  File "/.../dbt/core/dbt/parser/partial.py", line 316, in schedule_nodes_for_parsing
    self.remove_mssat_file(source_file)
KeyError: 'test.fishtown_internal_analytics.not_null_fct_cloud_accounts_has_successful_session.f841b7dce3'

06
=====================================================
line 411 in schedule_macro_nodes_for_parsing
parse_file_type = null
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/manifest.py", line 224, in load
    project_parser_files = partial_parsing.get_parsing_files()
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 134, in get_parsing_files
    self.delete_from_saved(file_id)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 203, in delete_from_saved
    self.delete_macro_file(saved_source_file, follow_references=True)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 353, in delete_macro_file
    self.handle_macro_file_links(source_file, follow_references)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 386, in handle_macro_file_links
    self.schedule_macro_nodes_for_parsing(referencing_nodes)
  File "/usr/local/lib/python3.8/dist-packages/dbt/parser/partial.py", line 411, in schedule_macro_nodes_for_parsing
    (key, name) = schema_file.get_key_and_name_for_test(node.unique_id)
AttributeError: 'SourceFile' object has no attribute 'get_key_and_name_for_test'

**Comment by gshank** [comment]
An additional error, when changing a disabled model to enabled:
      dbt.exceptions.CompilationException: Compilation Error
        dbt found two resources with the name "model_three". Since these resources have the same name,
        dbt will be unable to find the correct resource when ref("model_three") is used. To fix this,
        change the name of one of these resources:
        - model.test.model_three (models-a/model_three.sql)
        - model.test.model_three (models-a/model_three.sql)
